services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle install && yarn install && bin/dev"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
      - node_modules:/rails/node_modules
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db

volumes:
  postgres_data:
  node_modules:
  bundle:
